/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MesaController;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Mesa;

/**
 *
 * @author kira
 */
public class PesquisaMesaView extends javax.swing.JFrame {

      private List<Mesa> mesaList = new MesaController().listaMesas();
      private MesaView mesaView;
    /**
     * Creates new form PesquisaEleitorFrame
     */
    public PesquisaMesaView() {
        initComponents();
        mesaView = new MesaView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisaMesa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSelecionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa Mesas");
        setResizable(false);

        txtPesquisaMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaMesaActionPerformed(evt);
            }
        });
        txtPesquisaMesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaMesaKeyPressed(evt);
            }
        });

        jLabel1.setText("Descrição da Mesa");

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Selecionar", "Número", "Descrição", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnSelecionar))
                    .addComponent(jLabel1))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaMesaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaMesaKeyPressed
        try {
            MesaController cc = new MesaController();
            List<Mesa> c = cc.buscaMesaPorDescricao(txtPesquisaMesa.getText());
            if (!c.isEmpty()){
                preencher_jTable(c);
            }
            // preencher_jTable(c);
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro, tente novamente!\n"+e.getLocalizedMessage());
        }
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(this, "Mesa não localizada ou não existe!\n"+e.getLocalizedMessage());
        }

    }//GEN-LAST:event_txtPesquisaMesaKeyPressed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed

        //  for (int i = 0; i<eleitorList.toArray().length; i++){
            Iterator <Mesa> mesaLists = mesaList.iterator();
            int i = 0;
            while(mesaLists.hasNext()){
                Object check = jTable1.getValueAt(i, 0);

                //verifica se o check está selecionado
                if (check.equals(true)){

                    MesaController cc = new MesaController();
                    //pega o valor que esta na tabela, porem este eh de tipo objeto
                    Object mesa_ID_Objetct = jTable1.getValueAt(i, 1);

                    int mesa_id = Integer.parseInt(mesa_ID_Objetct.toString());
                    // JOptionPane.showMessageDialog(null,"Teste");

                    //setando os valores do eleitor selecionado no objeto eleitor

                    // eleitor.setEle_titulo(Integer.parseInt(tituloEleitorObject.toString()));
                    //         eleitor.setEle_nome(String.valueOf(nomeEleitorObject));
                    //       eleitor.setEle_RG(String.valueOf(rgEleitorObject));
                    //     eleitor.setEle_senha(String.valueOf(senhaEleitorObject));
                    //   eleitor.setTipo_ele_id(Integer.parseInt(tipoEleIdObject.toString()));

                    mesaView = new MesaView();

                    mesaView.setVisible(true);
                    try {
                        mesaView.recebeTitulo(mesa_id);
                    } catch (SQLException ex) {
                        Logger.getLogger(PesquisaMesaView.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    break;
                }

                i++;

            }
            // GetList();
            // PesquisaItem();

    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void txtPesquisaMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaMesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaMesaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaMesaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaMesaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaMesaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaMesaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPesquisaMesa;
    // End of variables declaration//GEN-END:variables
    
    public void preencher_jTable(List<Mesa> me){
         
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(1);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(1);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(1);
        

        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        
        for(Mesa mesa: me){ 
         
        modelo.addRow(new Object[] {null, mesa.getIdMesa(), mesa.getDescricao(), mesa.getStatus()});  
        }
    }
}
